<?php

namespace Proxies\__CG__\GPS\TrackerBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Appareil extends \GPS\TrackerBundle\Entity\Appareil implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCodeAppareil($codeAppareil)
    {
        $this->__load();
        return parent::setCodeAppareil($codeAppareil);
    }

    public function getCodeAppareil()
    {
        $this->__load();
        return parent::getCodeAppareil();
    }

    public function setUtilisateur(\GPS\TrackerBundle\Entity\Utilisateur $utilisateur = NULL)
    {
        $this->__load();
        return parent::setUtilisateur($utilisateur);
    }

    public function getUtilisateur()
    {
        $this->__load();
        return parent::getUtilisateur();
    }

    public function addCredential(\GPS\TrackerBundle\Entity\Credential $credentials)
    {
        $this->__load();
        return parent::addCredential($credentials);
    }

    public function removeCredential(\GPS\TrackerBundle\Entity\Credential $credentials)
    {
        $this->__load();
        return parent::removeCredential($credentials);
    }

    public function getCredentials()
    {
        $this->__load();
        return parent::getCredentials();
    }

    public function setTypeAppareil($typeAppareil)
    {
        $this->__load();
        return parent::setTypeAppareil($typeAppareil);
    }

    public function getTypeAppareil()
    {
        $this->__load();
        return parent::getTypeAppareil();
    }

    public function setNomAppareil($nomAppareil)
    {
        $this->__load();
        return parent::setNomAppareil($nomAppareil);
    }

    public function getNomAppareil()
    {
        $this->__load();
        return parent::getNomAppareil();
    }

    public function setDescAppareil($descAppareil)
    {
        $this->__load();
        return parent::setDescAppareil($descAppareil);
    }

    public function getDescAppareil()
    {
        $this->__load();
        return parent::getDescAppareil();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'codeAppareil', 'nomAppareil', 'typeAppareil', 'descAppareil', 'utilisateur', 'credentials');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}