<?php

namespace GPS\TrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppareilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppareilRepository extends EntityRepository
{
}
