<?php

namespace GPS\TrackerBundle\Entity;

use Doctrine\ORM\EntityRepository;
use GPS\TrackerBundle\Entity\Utilisateur;
use GPS\TrackerBundle\Entity\Appareil;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    public function isValidUser(Utilisateur $user){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT u from GPSTrackerBundle:Utilisateur u where
            u.login = :login and u.password = :password'
            )->setParameter('login', $user->getLogin())
            ->setParameter('password', $user->getPassword())
            ->getResult();
        if (count($query)>=1){
            return $query[0];
        }
        else {
            return null;
        }
    }

    public function addUser(Utilisateur $user){
        if (isValidUser($user))
            return false;
        else {
            $em = $this->getEntityManager();
            $em->persist($user);
            return true;
        }
    }

    public function db_addAppareil(Appareil $appareil){
        
    }
}
